# Use the latest Ubuntu image as the base
FROM ubuntu:latest

# Update APT package lists
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Set the default command to echo "Hello, World!"
CMD ["echo", "Hello, World!"]